name: CodeClimate PR Review

on:
  pull_request:
    branches:
      - master

jobs:
  codeclimate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run CodeClimate Analysis
        uses: docker://codeclimate/codeclimate
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          args: analyze
